package com.talentos.shared.entity;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

import java.util.UUID;

/**
 * Root mapped superclass for every TalentOS JPA entity.
 *
 * <p>Provides the UUID v4 primary key generated by the application layer
 * (strategy = AUTO with Hibernate's UUIDGenerator), keeping generation
 * consistent with the ERD decision: "UUID v4 — application-generated".
 *
 * <p>All entities extend either {@link BaseEntity} (for non-auditable tables
 * such as activity_logs) or {@link AuditableEntity} (for all mutable domain
 * tables that require the full audit trail).
 */
@MappedSuperclass
@Getter
@Setter
@NoArgsConstructor
@SuperBuilder
public abstract class BaseEntity {

    /**
     * Surrogate primary key — UUID v4 generated by Hibernate before INSERT.
     * Stored as a native {@code uuid} column in PostgreSQL via column definition.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false, columnDefinition = "uuid")
    private UUID id;
}
