spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/talentos}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
  jpa:
    show-sql: true
  flyway:
    clean-disabled: false # Allow cleaning DB in local development if needed

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    com.talentos: DEBUG
