package com.talentos.company.model;

import com.talentos.shared.entity.AuditableEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;
import org.hibernate.annotations.SQLRestriction;

import java.time.Instant;
import java.util.UUID;

/**
 * Persistent domain entity representing an organization that posts jobs
 * on the TalentOS platform.
 *
 * <p>Companies are created and managed by users with the {@code RECRUITER}
 * or {@code ADMIN} role. Every {@code Job} belongs to exactly one Company;
 * every {@code Recruiter} and {@code HiringManager} profile is associated
 * with exactly one Company.
 *
 * <h3>Table: {@code companies}</h3>
 *
 * <h3>Soft Delete</h3>
 * <p>Records are never physically deleted. When a company is removed the
 * service layer sets {@code isDeleted = true}, {@code deletedAt = Instant.now()},
 * and {@code deletedBy = <actor UUID>}. The {@code @SQLRestriction} annotation
 * ensures that all Spring Data JPA queries automatically exclude deleted rows
 * without any manual {@code WHERE} clause in the service layer.
 *
 * <h3>Relationships</h3>
 * <ul>
 *   <li>{@code jobs}          — one company → many jobs (mappedBy="company")</li>
 *   <li>{@code recruiters}    — one company → many recruiters (mappedBy="company")</li>
 *   <li>{@code hiringManagers}— one company → many hiring managers (mappedBy="company")</li>
 * </ul>
 * Collections are LAZY and initialized to empty {@link ArrayList} instances to
 * avoid accidental N+1 queries and NullPointerExceptions before first access.
 *
 * <p>This class contains <strong>no business logic, no repositories, no services,
 * and no controllers</strong> — it is a pure data carrier for the persistence layer.
 */
@Entity
@Table(
        name = "companies",
        uniqueConstraints = {
                // ERD §7 Unique Constraints: companies.slug
                @UniqueConstraint(name = "uq_companies_slug", columnNames = "slug")
        },
        indexes = {
                // ERD §8 Performance Indexes: filter active companies
                @Index(name = "idx_companies_is_deleted", columnList = "is_deleted"),

                // ERD §8 Full-Text Search: GIN index on name + description
                // Note: GIN functional index on to_tsvector is defined in Flyway migration;
                // declared here as a documentation anchor only — JPA cannot create GIN indexes.
                // The @Index below serves as a standard B-tree index on name for prefix searches.
                @Index(name = "idx_companies_name", columnList = "name")
        }
)
@SQLRestriction("is_deleted = false")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@SuperBuilder
public class Company extends AuditableEntity {

    // -------------------------------------------------------------------------
    // Core Identity Fields (ERD: companies table)
    // -------------------------------------------------------------------------

    /**
     * Human-readable company name displayed throughout the UI.
     * NOT NULL per ERD §7 Not Null Constraints.
     */
    @NotBlank(message = "Company name is required")
    @Size(max = 255, message = "Company name must not exceed 255 characters")
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /**
     * URL-safe unique identifier derived from {@link #name}.
     * Used in public-facing URLs (e.g., {@code /companies/acme-corp}).
     * Generated by {@code SlugUtils.toSlug(name)} in the service layer before persist.
     * NOT NULL + UNIQUE per ERD §7.
     */
    @NotBlank(message = "Company slug is required")
    @Size(max = 255, message = "Company slug must not exceed 255 characters")
    @Column(name = "slug", nullable = false, unique = true, length = 255)
    private String slug;

    /**
     * Long-form description of the company — rendered in the company profile page.
     * Nullable: optional at creation, encouraged but not enforced.
     * Stored as PostgreSQL {@code TEXT} (unbounded).
     */
    @Size(max = 5000, message = "Description must not exceed 5000 characters")
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * Industry sector the company operates in.
     * Examples: "Technology", "Finance", "Healthcare", "Education".
     * Nullable: optional metadata.
     */
    @Size(max = 100, message = "Industry must not exceed 100 characters")
    @Column(name = "industry", length = 100)
    private String industry;

    /**
     * Approximate headcount band.
     * Examples: "1-10", "11-50", "51-200", "201-500", "500+".
     * Stored as free-text per ERD; validation is done in the service/DTO layer.
     * Nullable: optional metadata.
     */
    @Size(max = 50, message = "Company size must not exceed 50 characters")
    @Column(name = "size", length = 50)
    private String size;

    /**
     * Company public website URL.
     * Nullable: not all companies have a website at registration time.
     */
    @Size(max = 500, message = "Website URL must not exceed 500 characters")
    @Column(name = "website_url", length = 500)
    private String websiteUrl;

    /**
     * Public URL to the company's logo image (hosted externally or in Supabase Storage).
     * Nullable: logo upload is optional.
     */
    @Size(max = 500, message = "Logo URL must not exceed 500 characters")
    @Column(name = "logo_url", length = 500)
    private String logoUrl;

    /**
     * City / region / country where the company is primarily headquartered.
     * Examples: "San Francisco, CA", "London, UK", "Remote".
     * Nullable: optional metadata.
     */
    @Size(max = 255, message = "Location must not exceed 255 characters")
    @Column(name = "location", length = 255)
    private String location;

    // -------------------------------------------------------------------------
    // Soft Delete Fields (ERD §10 — declared on entity, not on superclass)
    // deletedAt is inherited from AuditableEntity
    // -------------------------------------------------------------------------

    /**
     * Logical deletion flag.
     * {@code true}  = record is soft-deleted (excluded from all standard queries via @SQLRestriction).
     * {@code false} = record is active (default).
     * NOT NULL with database default {@code false}.
     */
    @Column(name = "is_deleted", nullable = false)
    @lombok.Builder.Default
    private boolean isDeleted = false;

    /**
     * UUID of the user who performed the soft delete.
     * Set exclusively by the service layer alongside {@code deletedAt} (inherited from {@link AuditableEntity}).
     * Nullable: NULL when the record has never been deleted.
     */
    @Column(name = "deleted_by", columnDefinition = "uuid")
    private UUID deletedBy;

    // -------------------------------------------------------------------------
    // Inverse Relationships (mappedBy — no FK column on this side)
    // -------------------------------------------------------------------------
    //
    // Inverse collections for jobs, recruiters, and hiringManagers are intentionally
    // omitted from this initial implementation. They will be added in their respective
    // feature branches once those entities are created, following this pattern:
    //
    //   @OneToMany(mappedBy = "company", fetch = FetchType.LAZY)
    //   @Builder.Default
    //   private List<Job> jobs = new ArrayList<>();
    //
    //   @OneToMany(mappedBy = "company", fetch = FetchType.LAZY)
    //   @Builder.Default
    //   private List<Recruiter> recruiters = new ArrayList<>();
    //
    //   @OneToMany(mappedBy = "company", fetch = FetchType.LAZY)
    //   @Builder.Default
    //   private List<HiringManager> hiringManagers = new ArrayList<>();
    //
    // Reason: adding them here before the owning entities exist causes a compilation
    // failure. The Company entity is complete per ERD schema — relationships are
    // enforced at the database level by the FK columns on the child tables.

    // -------------------------------------------------------------------------
    // Convenience Helper — no business logic
    // -------------------------------------------------------------------------

    /**
     * Returns {@code true} if this company has been logically deleted.
     * Delegates to the boolean flag rather than the inherited {@link #isSoftDeleted()}
     * which checks {@code deletedAt != null} — both should agree in practice.
     */
    public boolean isActive() {
        return !isDeleted;
    }
}
